talis/tripod-php

src/mongo/base/MongoTripodBase.class.php
src/mongo/delegates/MongoTripodSearchDocuments.class.php
src/mongo/delegates/MongoTripodUpdates.class.php
src/mongo/providers/MongoSearchProvider.class.php
test/unit/mongo/MongoSearchProviderTest.php
test/unit/mongo/MongoTripodQueueOperationsTest.php

This fixes a problem with Mongos vs. 2.6.+ where using 
```php 
while($cursor->hasNext()) {
$result = $cursor->getNext();
```
causes ``` $result ``` to be empty.  It's not clear if this is a bug in php-mongo or mongo, but we've seen it consistently in 2.6+.  This should be backwards compatible with any versions of Mongo 2.0+

90%: Sidestep cursor problems

---

scripts/mongo/createTables.php
scripts/mongo/createTables2.php
scripts/mongo/createViews2.php
scripts/mongo/processQueue2.php
test/performance/rest-interface/bulkGenerateTablesViewsSearchDocs.php

This PR is the start of deprecating the old tripod scripts for generating views, tables, etc. so we can use getopts (rather than argument order) and include stats monitoring, etc.
Currently, they run alongside the old scripts until we can identify and remove all references to the old ones.

90%: Scripts redesign

---

src/mongo/MongoTripodConfig.class.php
test/unit/mongo/MongoTripodConfigTest.php

Tripod is currently using the queue db to store transaction logs.  Fixed this, and added a test to ensure queues and transaction logs stick to their own dbs.

90% - Use correct config array when getting the transaction log db

---

src/mongo/delegates/MongoTripodSearchIndexer.class.php
src/mongo/delegates/MongoTripodTables.class.php
src/mongo/delegates/MongoTripodViews.class.php
src/mongo/util/IndexUtils.class.php

I found when working on #56 that IndexUtils wasn't properly updated to deal with multiple datasources, which causes failures when it runs across tablespecs, viewspecs, and search document specs.
This branch excludes views, search, and table indexes from the regular index regeneration process and then specifically handles views and table rows (search indexes are done via some other mechanism).

90%: Treat tables, views, and search differently

---

scripts/mongo/createSearchDocuments.php
scripts/mongo/createTables.php
scripts/mongo/createViews.php
src/mongo/MongoTripodConfig.class.php
src/mongo/base/CompositeBase.class.php
src/mongo/delegates/MongoTransactionLog.class.php
src/mongo/delegates/MongoTripodSearchIndexer.class.php
src/mongo/delegates/MongoTripodTables.class.php
src/mongo/delegates/MongoTripodViews.class.php
test/unit/mongo/MongoTripodTablesTest.php

This refactors the createTables and createViews scripts to allow them to push the actual regeneration to the resque queue.  You may also specify which queue you want these to go on, so as not to clog the regular process queue.
It also introduces a createSearchDocuments script which never existed in Tripod.
The major difference between these and how they work currently is that the current version loops over the CBDs and generates the composites serially.  This version gives the option to loop over the CBDs and submits a job to generate the composite, so the actual generation can be scaled/stopped as needed without starting from the beginning to resume.
If you don't pass the -a/--async flag it works exactly as it does now.

90%: Queue bulk composite generation

---

scripts/mongo/createSearchDocuments.php
scripts/mongo/createTables.php
scripts/mongo/createViews.php
src/mongo/delegates/SearchIndexer.class.php
src/mongo/delegates/Tables.class.php
src/mongo/delegates/Views.class.php
src/mongo/jobs/ApplyOperation.class.php
src/mongo/jobs/DiscoverImpactedSubjects.class.php
test/unit/mongo/ApplyOperationTest.php
test/unit/mongo/DiscoverImpactedSubjectsTest.php

This branch refactors ApplyOperation somewhat so that it works with an array of ImpactedSubjects rather than just one.  This produces a massive performance benefit by requiring fewer forked processes for every DiscoverImpactedSubjects job submitted.

90%: Apply operation multiple subjects

---

src/mongo/jobs/ApplyOperation.class.php
src/mongo/jobs/DiscoverImpactedSubjects.class.php
test/unit/mongo/ApplyOperationTest.php
test/unit/mongo/DiscoverImpactedSubjectsTest.php

This change ensures that all operations queued through ` ApplyOperation->createJob() ` or DiscoverImpactedSubjects->createJob() ` either use the default queue names or are namespaced under the default queue name.
For example, if a specification contains the ‘queue’ attribute ‘wibble’, it will be placed either in:
` tripod::{$APP_ENV}::apply::wibble `
or
` tripod::apply::wibble `
(depending whether or not $APP_ENV is set)
If you manually set a queue on Tripod init:
```php
$tripod = new \Tripod\Mongo\Driver(‘CBD_foo’, ‘foo’, array(OP_ASYNC=>array(OP_QUEUE=>’foobar’));
```
operations would be sent to:
` tripod::$APP_ENV::discover::foobar `
` tripod::$APP_ENV::apply::foobar `
or 
` tripod::discover::foobar `
` tripod::apply::foobar `
if $APP_ENV isn’t set.

90%: All queues (manually sent or defined in specs) should be namespaced

---

src/exceptions/JobException.class.php
src/mongo/Config.class.php
src/mongo/base/JobBase.class.php
src/tripod.inc.php
test/unit/mongo/ApplyOperationTest.php

We can't rely on `php-resque` to always throw exceptions on its own so we also do a hack to check the status to make sure the job is def in the queue.
Backs off for 1s with 5 retries if a job isn't added to the queue.

90% - Detects/Retries a failed request to resque

---

src/classes/ExtendedGraph.class.php
src/mongo/MongoGraph.class.php
test/unit/ExtendedGraphTest.php
test/unit/mongo/MongoGraphTest.php

To address issue https://github.com/talis/tripod-php/issues/81
This will ensure that subjects, predicates, and resource values are always strings.  Literal values can be any scalar - we would like to enforce strings for literal values too, but doing so may break legacy databases which use non-strings as values.

90% - Prevent null values being added to ExtendedGraph

---

src/mongo/delegates/Tables.class.php
test/unit/mongo/MongoTripodConfigTest.php
test/unit/mongo/MongoTripodDriverTest.php
test/unit/mongo/MongoTripodNQuadSerializerTest.php
test/unit/mongo/MongoTripodTablesTest.php
test/unit/mongo/data/config.json
test/unit/mongo/data/resources.json

Mongo 2.6 has introduced stricter enforcement of the maximum
index key size. By default an index key > 1024 bytes now throws
an exception. This pull requests changes Table Row generation
to capture this error when thrown. The key is then truncated
and the save retried.

90% Handle Mongo 2.6's stricter enforcement of index key sizes.

---

src/mongo/delegates/SearchDocuments.class.php
test/unit/mongo/MongoSearchProviderTest.php
test/unit/mongo/MongoTripodSearchDocumentsTest.php
test/unit/mongo/data/searchData.json

This utf8_encode is garbling diacritics for search documents.  While adding tests I also discovered that strtolower while building the search indices was also causing utf8 issues with the indices. 
## Issue 1
The utf8_encode function is only designed to convert from ISO-8859-1 to UTF-8.  If we pass a utf8 string through this method then anything outside of the normal ASCII range will be converted as if it is ISO-8859-1, resulting in garbled strings.  See the top answer here for a better explanation: http://stackoverflow.com/questions/6700275/utf8-encode-function-purpose
If we still care about converting to UTF-8 here then we would need to think about something along the lines of: iconv(mb_detect_encoding($text, mb_detect_order(), true), "UTF-8", $text), as per …

90% - Remove incorrect char encoding

---

src/classes/StatsD.class.php
src/mongo/MongoTripodConstants.php
src/mongo/base/DriverBase.class.php
src/mongo/base/JobBase.class.php
test/unit/mongo/MongoTripodDriverTest.php
test/unit/mongo/MongoTripodStatTest.php

This PR brings in 2 changes:
1. it fixes a bug where queue stats weren't actually getting sent: `JobBase->getStat()` was using `isset($this->statConfig)` to determine if there was already a config set, but since it defaults to an array, it also needed to check if it was empty
2. It rips out the faulty understanding of the stats prefix and hard codes both "by store" (database) and aggregate stats with each stats send

90%: Fix queue stats

---

src/mongo/Config.class.php
src/mongo/base/DriverBase.class.php
test/unit/mongo/MongoTripodConfigTest.php
test/unit/mongo/MongoTripodViewsTest.php

If there is momentary blip in comms, the mongo php driver handles it (or is supposed to). What it doesn't handle however, is a step down for the primary on the repset.
In that instance, we get a 500 error with "No candidate servers found", when really it should back off and try again. The connection will be available in a few seconds once a new primary is elected and then the code can continue as per normal.
As far as i can tell, the mongo PHP driver does not support this so we're going to create something to do it for us.
You get 2 exceptions in Tripod when there are blips (step downs) in the rep set. The first one is when the rep set is down when you attempt to connect to it (`MongoConnectionException`). You also get one when the rep set is up when you connect, but down when you try to …

90% TENT-1872 Add retry logic to tripod

---

.travis.yml
README.md
composer.json
scripts/mongo/discoverUnnamespacedUris.php
src/mongo/Config.class.php
src/mongo/Driver.class.php
src/mongo/ImpactedSubject.class.php
src/mongo/base/CompositeBase.class.php
src/mongo/base/DriverBase.class.php
src/mongo/base/JobBase.class.php
src/mongo/delegates/SearchDocuments.class.php
src/mongo/delegates/SearchIndexer.class.php
src/mongo/delegates/Tables.class.php
src/mongo/delegates/TransactionLog.class.php
src/mongo/delegates/Updates.class.php
src/mongo/delegates/Views.class.php
src/mongo/providers/MongoSearchProvider.class.php
src/mongo/util/IndexUtils.class.php
src/mongo/util/TriplesUtil.class.php
test/rest-interface/vagrant/bootstrap.sh
test/unit/mongo/MongoSearchProviderTest.php
test/unit/mongo/MongoTransactionLogTest.php
test/unit/mongo/MongoTripodConfigTest.php
test/unit/mongo/MongoTripodDocumentStructureTest.php
test/unit/mongo/MongoTripodDriverTest.php
test/unit/mongo/MongoTripodTablesTest.php
test/unit/mongo/MongoTripodTestBase.php
test/unit/mongo/MongoTripodTransactionRollbackTest.php
test/unit/mongo/MongoTripodViewsTest.php

This is to support the new mongo driver for PHP.
The PHP drivers implement a different API, so all chainable calls such as `->find()->sort()->limit()` have been replaced with another format. Read preferences have changed (how you set them), so have some of the function calls. An upgrade guide can be found here: https://mongodb.github.io/mongo-php-library/upgrade-guide/
There are some requirement changes:
- Mongo 2.6.x and above. This has changed from requiring Mongo 2.x - the reason for this is the way an `updateOne` or `replaceOne` function works with the current functionality with the new PHP mongo library. If we want to support older versions of Mongo, we'll need to change some functionality.
- PHP 5.4+. The MongoDB PHP library only works with PHP 5.4 and above - so we're tied to this. …

Issue #109 Upgrade to latest PHP driver

---

src/mongo/delegates/Tables.class.php
src/mongo/providers/MongoSearchProvider.class.php

We are seeing some intermittent failures in both the app and in workers.
What is happening is that `updateOne` takes either an array or an object. If it's an array, it is supposed to be a filter - so `['match' => 'value']`. If it's an object, it should be an ObjectId.
However - in Tripod, our `_id` fields are arrays - so validation on the updateOne function is ok - but it won't match. By changing it to be `['_id' => $generatedRow['_id']]` we make sure the filter works as expected. 
The update to MongoSearchProvider is where we are doing an insert where we should be using an upsert.

Updated updateOne queries

---

src/mongo/delegates/Tables.class.php
test/unit/mongo/MongoTripodComputedFieldsTest.php
test/unit/mongo/MongoTripodTestBase.php
test/unit/mongo/data/dates.json

When using a conditional in a table spec that compares 2 date objects, the comparison fails because the 2 objects aren't in a state that can be compared. 
`UTCDateTime` cannot be compared using comparison operators `UTCDateTime`. A `DateTime` object however, can be.

Cast UTCDateTime to a DateTime object for comparison

---

.travis.yml
src/classes/ExtendedGraph.class.php
test/unit/mongo/MongoTripodConfigTest.php
test/unit/mongo/MongoTripodDriverTest.php
test/unit/mongo/data/config.json

To avoid PHP warnings we need to convert this line:
```
$this->_add_arc2_triple_list($parser->getTriples());
```
into:
```
$triples = $parser->getTriples();
$this->_add_arc2_triple_list($triples);
```
This was done originally in the `add_turtle` method, but not others.
Other changes here are to do with test config for mongo connection strings. Without a hostname delimiter (the slash), you get this error when running the build under PHP 7.0:
```
MongoDB\Driver\Exception\InvalidArgumentException: Failed to parse MongoDB URI: 'mongodb://localhost?connectTimeoutMS=20000'. Expected end of hostname delimiter.
```
This fixes that up.

Reference fix for PHP 7.0

---

.editorconfig
.gitignore
.travis.yml
composer.json
docker-compose.yml
src/mongo/Config.class.php
src/mongo/JobGroup.php
src/mongo/MongoTripodConstants.php
src/mongo/delegates/SearchDocuments.class.php
src/mongo/delegates/SearchIndexer.class.php
src/mongo/delegates/Tables.class.php
src/mongo/delegates/Views.class.php
src/mongo/jobs/ApplyOperation.class.php
src/mongo/providers/MongoSearchProvider.class.php
src/mongo/util/IndexUtils.class.php
src/tripod.inc.php
test/unit/mongo/ApplyOperationTest.php
test/unit/mongo/IndexUtilsTest.php
test/unit/mongo/MongoSearchProviderTest.php
test/unit/mongo/MongoTripodTablesTest.php
test/unit/mongo/MongoTripodViewsTest.php

This adds the ability to track 'bulk' apply operations jobs (e.g. regenerate all views, table rows, etc.) and, when complete, delete any stale composite documents that have an earlier (or missing) timestamp from when the bulk job started.
This does so by adding a `_cts` (i.e. 'Created timestamp') field on the composites.

ENT-71: regenerate composites without clearing collection first

---

composer.json
src/mongo/delegates/Views.class.php
test/unit/mongo/MongoTripodConfigTest.php
test/unit/mongo/MongoTripodTestBase.php
test/unit/mongo/MongoTripodViewsTest.php
test/unit/mongo/data/config.json
test/unit/mongo/data/resources.json

This change lets view spec TTLs be `-1` which essentially means they never change unless the original graph is deleted or changes its rdf type.

Non-invalidating views

---

.travis.yml
composer.json
docker-compose.yml
src/mongo/Config.class.php
src/mongo/Driver.class.php
src/mongo/IConfigInstance.php
src/mongo/base/CompositeBase.class.php
src/mongo/delegates/SearchIndexer.class.php
src/mongo/delegates/Tables.class.php
src/mongo/delegates/Views.class.php
test/unit/mongo/MongoTripodSearchIndexerTest.php
test/unit/mongo/MongoTripodTablesTest.php
test/unit/mongo/MongoTripodViewsTest.php

Presently, an individual job is queued for each document that needs composite generation.  This causes an unnecessary bottleneck by queuing up (potentially) many ApplyOperation Resque jobs to update one resource: Resque needs to contact Redis, then make a Mongo connection, do validation, etc. perform a very small update, then close the mongo connection, etc.
A much more efficient way to do this is to *batch* the ApplyOperation jobs with, e.g., 100 table row operations.  It's already designed to work this way, we just aren't utilizing it.

Batch generate composites

---

src/classes/StatsD.class.php

We are using `fsockopen` to create a stream so we can, connect and write to our StatsD server via UDP:
```php
if (!empty($this->host)) // if host is configured, send..
{
$fp = fsockopen("udp://{$this->host}", $this->port);
if (! $fp) { return; }
foreach ($sampledData as $stat => $value)
{
if (is_array($value))
{
foreach ($value as $v)
{
fwrite($fp, "$stat:$v");
}
}
else
{
fwrite($fp, "$stat:$value");
}
}
fclose($fp);
}
}
``` 
From the PHP manual for fsockopen
```
The socket will by default be opened in blocking mode. You can switch it to non-blocking mode by using stream_set_blocking().
```
However, we are not telling PHP to make the stream non-blocking. As a consequence when this attempts to write to the StatsD server if the UDP buffer on the server is full, this call will block on the …

fsockopen UDP connections should be non-blocking

---

src/classes/StatsD.class.php
test/unit/mongo/MongoTripodDriverTest.php
test/unit/mongo/MongoTripodStatTest.php

If you have a statsd host configured, whenever there is a request to send stats, we work out which stats paths to send data to.
As well as stats about the current operation, in a pretty straight forward `myapp.tripod.MONGO_SOMETHING` we also send `myapp.tripod.group_by_db.db_name.MONGO_SOMETHING`.
There are known issues with statsd sending this data in a blocking fashion, rather than non-blocking, so having more data, that is verbose and as it turns out, really not that useful (we have been blacklisting these stats for years), makes the app run slower.
By reducing the amount of data, we reduce the [number of loops](https://github.com/talis/tripod-php/blob/master/src/classes/StatsD.class.php#L109) we do, which means that we block the operation for less. This means a more performant app.

Remove ref to getStoreStatPath

---

.travis.yml
README.md

The travis builds of talis-php started failing with this error recently. 
See https://github.com/talis/talis-php/pull/16
> This PR installs ant to fix the 5.6 to 7.2 inclusive builds.
> The build image is pinned to trusty which is needed to be able to install PHP 5.5. (This may mean that ant is installed by default without specifying it explicitly, but we are using it, and when we do move to Xenial or later it might not be there. We're using it - lets be explicit. )
Resolves https://github.com/talis/platform/issues/4133

Fix build by pinning to trusty

---

src/mongo/base/DriverBase.class.php

Upon trying to make TARL logging a bit more sane with a default log level of INFO, it was spotted that `tripod-php` was sending timing logs to INFO level, but also had a comment against the line querying whether this should be DEBUG.
Change the `timingLog` log level to DEBUG as these are absolutely not INFO level logs.

Change timingLog level from INFO to DEBUG

---

.circleci/config.yml
docker-compose.yml

* Related to https://github.com/talis/platform/issues/6747
* Bump Mongo to 3.2.
* Pin version of redis - ran into an issue with it on CircleCI, 
see https://discuss.circleci.com/t/redis-fatal-cant-initialize-background-jobs/48376

PLAT-6747 Bump Mongo to 3.2 in development and build

---

src/classes/ExtendedGraph.class.php
test/unit/ExtendedGraphTest.php

* Related to [PLT-71](https://techfromsage.atlassian.net/browse/PLT-71)
* Check if given subject and predicate are set on the index in `remove_{resource|literal}_triple`.
* Refactor check for subject and predicate in `get_first_resource` to ensure non-null value.
* Add unit tests for these methods.
[PLT-71]: https://techfromsage.atlassian.net/browse/PLT-71?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PLT-71 Fix Undefined array key in remove triple

---

src/mongo/util/IndexUtils.class.php
test/unit/mongo/IndexUtilsTest.php

* Related to PLT-856
* Fixes #105 -  
if `reindex` is set to true, there was a possibility that the same collection would be referenced in more than one place; in that case, indexes previously created for a config would be dropped while creating indexes for another config.
* Update legacy method name `deleteIndexes` → `dropIndexes` https://www.mongodb.com/docs/php-library/upcoming/upgrade/

PLT-856 Fix ensureIndexes with `$reindex = true`
